### ISSUE TITLE
Can ScratchPlayer run ios or android？Would you please upload an effect drawing？Thank you！

### ISSUE THREAD

**Issue by lianghuiyuan** [gangseok514/ScratchPlayer#1]
Hi, Can ScratchPlayer run ios or android？Would you please upload an effect drawing？Thank you！

**Comment by gangseok514** [comment]
i'm not chinese. korean.
but i can mostly understand what you are saying by translator.

i just fixed talkbubble and minor issues.
maybe you can play simple examples.
but as i know there are many issues like sound, collision detect remain.
2015. 12. 8. 오후 10:50에 "Mr.L" notifications@github.com님이 작성:

**Comment by lianghuiyuan** [comment]
Thank you so much. 
Sorry for automatically writting in Chinese.
I will play some simple examples.
